[package]
name = "brainheck"
description = "Brainheck interpreter written in Rust."
version = "0.1.4"
authors = ["Vanessa McHale <tmchale@wisc.edu>"]
license-file = "LICENSE"
exclude = [
    "bf/*",
    ".gitignore",
]
documentation = "https://github.com/vmchale/brainh-ck#README"
homepage = "https://github.com/vmchale/brainh-ck"
repository = "https://github.com/vmchale/brainh-ck"
keywords = ["brainfuck","brainheck","esolang"]
readme = "README.md"

[dependencies]
clap = {version = "2.20.4", features = ["yaml"]}

[lib]
name = "brainheck"
path = "src/lib.rs"

[[bin]]
name = "bh"
path = "src/main.rs"
